web/router.ex
defmodule Uptom.Router do
  use Uptom.Web, :router
  use Coherence.Router
  use Plug.ErrorHandler

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, db_model: Uptom.User
    # plug :current_user
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, db_model: Uptom.User, protected: true
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    pipe_through :browser
    coherence_routes()
  end

  scope "/" do
    pipe_through :protected
    coherence_routes :protected
  end

  scope "/", Uptom do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    get "/health", HealthController, :index

    get "/login", SessionController, :new
    post "/session", SessionController, :create
    get "/logout", SessionController, :delete
    get "/join", RegistrationController, :new
    post "/register", RegistrationController, :create
    get "/passwords/new", PasswordController, :new
    post "/passwords", PasswordController, :reset
  end

  # Registered User Zone
  scope "/", Uptom do
    pipe_through :protected

    resources "/sites", SiteController
  end


  # Other scopes may use custom stacks.
  # scope "/api", Uptom do
  #   pipe_through :api
  # end

  defp handle_errors(conn, %{kind: kind, reason: reason, stack: stacktrace}) do
    conn =
      conn
      |> Plug.Conn.fetch_cookies()
      |> Plug.Conn.fetch_query_params()

    conn_data = %{
      "request" => %{
        "cookies" => conn.req_cookies,
        "url" => "#{conn.scheme}://#{conn.host}:#{conn.port}#{conn.request_path}",
        "user_ip" => (conn.remote_ip |> Tuple.to_list() |> Enum.join(".")),
        "headers" => Enum.into(conn.req_headers, %{}),
        "params" => conn.params,
        "method" => conn.method,
      }
    }

    Rollbax.report(kind, reason, stacktrace, %{}, conn_data)
  end
end

web/views/coherence/layout_view.ex
defmodule Coherence.LayoutView do
  use Uptom.Web, :view


end

web/views/layout_view.ex
defmodule Uptom.LayoutView do
  use Uptom.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Uptom</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <style>
      html { font-family: PT Sans, sans-serif; }
      .brand-logo { font-weight: 900; }
      #welcome-text { font-weight: 700; }

      body {
        display: flex;
        min-height: 100vh;
        flex-direction: column;
      }

      #main {
        flex: 1 0 auto;
      }

    </style>
  </head>

  <body>
    <nav class="" role="navigation">
      <div class="nav-wrapper container"><a id="logo-container" href="/" class="brand-logo">upTom<span class="green-text text-accent-4">.</span></a>
        <ul class="right hide-on-med-and-down">
          <%= if Coherence.logged_in?(@conn) do %>
            <li><%= link "Log out", to: session_path(@conn, :delete), method: :delete %></li>
          <% else %>
            <li><%= link "Login", to: session_path(@conn, :new) %></li>
            <li><%= link "Register", to: registration_path(@conn, :new) %></li>
          <% end %>
        </ul>

        <ul id="nav-mobile" class="side-nav">
          <%= if Coherence.logged_in?(@conn) do %>
            <li><%= link "Sites", to: site_path(@conn, :index) %></li>
            <li><%= link "Log out", to: session_path(@conn, :delete), method: :delete %></li>
          <% else %>
            <li><%= link "Login", to: session_path(@conn, :new) %></li>
            <li><%= link "Register", to: registration_path(@conn, :new) %></li>
          <% end %>

        </ul>
        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
      </div>
    </nav>

    <div id="main" class="container">
      <div class="alert-container">
        <%= if get_flash(@conn, :info) do %><p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p><% end %>
        <%= if get_flash(@conn, :error) do %><p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p><% end %>
      </div>

        <%= render @view_module, @view_template, assigns %>

    </div>





    <footer class="page-footer grey darken-3">
      <div class="footer-copyright">
        <div class="container">
        Made by <a class="grey-text text-lighten-3" href="http://levente.bagi.name">Levente Bagi</a>
        </div>
      </div>
    </footer>




    <!--  Scripts-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>
      $(document).ready(function() {
        $('select').material_select();
      });
    </script>

  </body>

</html>

web/templates/layout/email.html.eex
<html>
  <head>
    <title><%= @email.subject %></title>
  </head>
  <body>
    <%= render @view_module, @view_template, assigns %>
  </body>
</html>

web/templates/layout/email.text.eex
<%= render @view_module, @view_template, assigns %>