web/router.ex
defmodule Uptom.Router do
  use Uptom.Web, :router
  use Coherence.Router
  use Plug.ErrorHandler

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, db_model: Uptom.User
    # plug :current_user
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, db_model: Uptom.User, protected: true
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    pipe_through :browser
    coherence_routes()
  end

  scope "/" do
    pipe_through :protected
    coherence_routes :protected
  end

  scope "/", Uptom do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    get "/health", HealthController, :index

    get "/login", SessionController, :new
    post "/session", SessionController, :create
    get "/logout", SessionController, :delete
    get "/join", RegistrationController, :new
    post "/register", RegistrationController, :create
    get "/passwords/new", PasswordController, :new
    post "/passwords", PasswordController, :reset
  end

  # Registered User Zone
  scope "/", Uptom do
    pipe_through :protected

    resources "/sites", SiteController
  end


  # Other scopes may use custom stacks.
  # scope "/api", Uptom do
  #   pipe_through :api
  # end

  defp handle_errors(conn, %{kind: kind, reason: reason, stack: stacktrace}) do
    conn =
      conn
      |> Plug.Conn.fetch_cookies()
      |> Plug.Conn.fetch_query_params()

    conn_data = %{
      "request" => %{
        "cookies" => conn.req_cookies,
        "url" => "#{conn.scheme}://#{conn.host}:#{conn.port}#{conn.request_path}",
        "user_ip" => (conn.remote_ip |> Tuple.to_list() |> Enum.join(".")),
        "headers" => Enum.into(conn.req_headers, %{}),
        "params" => conn.params,
        "method" => conn.method,
      }
    }

    Rollbax.report(kind, reason, stacktrace, %{}, conn_data)
  end
end

web/views/coherence/coherence_view.ex
defmodule Coherence.CoherenceView do
  use Uptom.Coherence.Web, :view
end

web/views/coherence/confirmation_view.ex
defmodule Coherence.ConfirmationView do
  use Uptom.Coherence.Web, :view

end

web/views/coherence/email_view.ex
defmodule Coherence.EmailView do
  use Uptom.Coherence.Web, :view

end

web/views/coherence/layout_view.ex
defmodule Coherence.LayoutView do
  use Uptom.Web, :view


end

web/views/coherence/password_view.ex
defmodule Coherence.PasswordView do
  use Uptom.Coherence.Web, :view

end

web/views/coherence/registration_view.ex
defmodule Coherence.RegistrationView do
  use Uptom.Coherence.Web, :view

end

web/views/coherence/session_view.ex
defmodule Coherence.SessionView do
  use Uptom.Coherence.Web, :view


end

web/views/coherence/unlock_view.ex
defmodule Coherence.UnlockView do
  use Uptom.Coherence.Web, :view


end

web/templates/coherence/password/edit.html.eex
<%= centered_card "Create a New Password" do %>
  <%= form_for @changeset, password_path(@conn, :update, @changeset.data), [as: :password], fn f  -> %>

    <%= hidden_input f, :reset_password_token %>

    <div class="form-group">
      <%= required_label f, :password, class: "control-label" %>
      <%= password_input f, :password, class: "form-control", required: "" %>
      <%= error_tag f, :password %>
    </div>

    <div class="form-group">
      <%= required_label f, :password_confirmation, class: "control-label" %>
      <%= password_input f, :password_confirmation, class: "form-control", required: "" %>
      <%= error_tag f, :password_confirmation %>
    </div>

    <div class="form-group">
      <%= submit "Update Password", class: "btn btn-primary" %>
      <%= link "Cancel", to: Coherence.Config.logged_out_url("/"), class: "btn" %>
    </div>
  <% end %>
<% end %>

web/templates/coherence/password/new.html.eex
<%= centered_card "Send reset password link" do %>
  <%= form_for @changeset, password_path(@conn, :create), [as: :password], fn f  -> %>

    <div class="form-group">
      <%= required_label f, :email, class: "control-label" %>
      <%= text_input f, :email, class: "form-control", required: "" %>
      <%= error_tag f, :email %>
    </div>

    <div class="form-group">
      <%= submit "Reset Password", class: "btn btn-primary" %>
      <%= link "Cancel", to: Coherence.Config.logged_out_url("/"), class: "btn" %>
    </div>
  <% end %>
<% end %>